import type { SubscriptionItem, SubscriptionStatus } from "../types";
import { useSubscriptionStore } from "../store";
import { formatUsd } from "../utils/money";
import { ExternalLink, Mail, AlertTriangle } from "lucide-react";
function statusLabel(status: SubscriptionStatus): string {
  return { need_confirm: "待确认", apple_unresolved: "Apple 待补录", flagged: "已确认闲置", cancel_in_progress: "退订中", cancelled: "已取消", verified_saved: "已验证节省", cancellation_failed: "退订失败", active: "仍在使用", ignored: "已忽略" }[status];
}
function mailto(item: SubscriptionItem): string {
  const subject = encodeURIComponent(`Cancellation Request for ${item.software_name}`);
  const body = encodeURIComponent(`Hello,\n\nPlease cancel my subscription for ${item.software_name} immediately and do not charge my card for the next billing cycle.\n\nSoftware: ${item.software_name}\nMerchant: ${item.merchant_name || ""}\n\nThank you.`);
  return `mailto:${item.support_email || ""}?subject=${subject}&body=${body}`;
}
export function SubscriptionCard({ item }: { item: SubscriptionItem }) {
  const updateStatus = useSubscriptionStore(s => s.updateStatus);
  return <article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200">
    <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold text-slate-900">{item.software_name}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{statusLabel(item.status)}</span>{item.status === "apple_unresolved" ? <span className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2.5 py-1 text-xs font-medium text-amber-700"><AlertTriangle className="h-3.5 w-3.5"/> 需要 Apple 收据</span> : null}</div><p className="mt-1 text-sm text-slate-500">商户：{item.merchant_name || "未知"} · 原始金额：{item.amount} {item.currency} · 周期：{item.billing_cycle}</p><p className="mt-1 text-sm text-slate-500">月化成本：<span className="font-semibold text-slate-900">{formatUsd(item.monthly_cost_usd)}</span> · 置信度：{Math.round(item.confidence * 100)}%</p><p className="mt-2 text-sm text-slate-600">{item.evidence}</p>{item.risk_note ? <p className="mt-2 text-sm text-amber-700">{item.risk_note}</p> : null}</div><div className="flex flex-wrap gap-2 md:justify-end"><button className="rounded-lg border border-slate-300 px-3 py-2 text-sm" onClick={() => updateStatus(item.id, "active")}>还在用</button><button className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-800" onClick={() => updateStatus(item.id, "flagged")}>确认闲置</button><button className="rounded-lg border border-blue-300 bg-blue-50 px-3 py-2 text-sm text-blue-800" onClick={() => updateStatus(item.id, "cancel_in_progress")}>去取消</button><button className="rounded-lg border border-emerald-300 bg-emerald-50 px-3 py-2 text-sm text-emerald-800" onClick={() => updateStatus(item.id, "cancelled")}>已取消</button><button className="rounded-lg border border-slate-300 px-3 py-2 text-sm" onClick={() => updateStatus(item.id, "ignored")}>忽略</button></div></div>
    {(item.status === "cancel_in_progress" || item.status === "apple_unresolved") ? <div className="mt-4 rounded-xl bg-slate-50 p-4">{item.status === "apple_unresolved" ? <p className="mb-3 text-sm text-slate-700">这是一笔 Apple 模糊扣费。请在邮箱搜索 <b>Your receipt from Apple</b>，粘贴 Apple 收据重新分析，才能拆出具体 App。</p> : null}{item.guide_steps.length > 0 ? <ol className="mb-3 list-decimal space-y-1 pl-5 text-sm text-slate-700">{item.guide_steps.map(step => <li key={step}>{step}</li>)}</ol> : <p className="mb-3 text-sm text-slate-700">暂无官方路径，建议使用搜索兜底或发送退订邮件。</p>}<div className="flex flex-wrap gap-2">{item.cancel_url ? <a className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-sm text-white" href={item.cancel_url} target="_blank" rel="noreferrer">打开管理页 <ExternalLink className="h-4 w-4"/></a> : null}{item.fallback_search_url ? <a className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700" href={item.fallback_search_url} target="_blank" rel="noreferrer">搜索退订方法 <ExternalLink className="h-4 w-4"/></a> : null}<a className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700" href={mailto(item)}>生成退订邮件 <Mail className="h-4 w-4"/></a></div></div> : null}
  </article>;
}
