from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class ObjectInfo:
    size: int
    content_type: str | None = None


class ObjectStorage(Protocol):
    def presign_upload(self, key: str, content_type: str, expires: int) -> str: ...

    def presign_download(self, key: str, expires: int) -> str: ...

    def move(self, source: str, destination: str) -> None: ...

    def delete(self, key: str) -> None: ...

    def stat(self, key: str) -> ObjectInfo: ...

    def read_prefix(self, key: str, limit: int) -> bytes: ...

    def write_bytes(self, key: str, data: bytes, content_type: str) -> None: ...

    def read_bytes(self, key: str) -> bytes: ...

    def ping(self) -> bool: ...
