"""create invoice accounting automation

Revision ID: 20260611_0011
Revises: 20260611_0010
Create Date: 2026-06-12 09:18:43.451678
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '20260611_0011'
down_revision: str | None = '20260611_0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(length=40), nullable=False),
    sa.Column('scope_value', sa.String(length=180), nullable=False),
    sa.Column('account_code', sa.String(length=80), nullable=False),
    sa.Column('tax_code', sa.String(length=80), nullable=False),
    sa.Column('cost_center', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('project', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_mappings')),
    sa.UniqueConstraint('organization_id', 'scope_type', 'scope_value', name='uq_accounting_mappings_scope')
    )
    op.create_index(op.f('ix_accounting_mappings_organization_id'), 'accounting_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounting_mappings_scope_type'), 'accounting_mappings', ['scope_type'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=180), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('vendor_name', sa.String(length=180), nullable=False),
    sa.Column('vendor_name_normalized', sa.String(length=180), nullable=False),
    sa.Column('invoice_number', sa.String(length=120), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('exception_codes_json', sa.Text(), nullable=False),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['invoices.id'], name=op.f('fk_invoices_duplicate_of_id_invoices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_invoices_org_idempotency'),
    sa.UniqueConstraint('organization_id', 'source_type', 'external_id', name='uq_invoices_org_source_external')
    )
    op.create_index(op.f('ix_invoices_duplicate_of_id'), 'invoices', ['duplicate_of_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_name_normalized'), 'invoices', ['vendor_name_normalized'], unique=False)
    op.create_table('accounting_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=180), nullable=True),
    sa.Column('external_version', sa.Integer(), nullable=True),
    sa.Column('exported_invoice_version', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('diff_json', sa.Text(), nullable=False),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_accounting_exports_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_exports')),
    sa.UniqueConstraint('invoice_id', 'provider', name='uq_accounting_exports_invoice_provider'),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_accounting_exports_invoice_id')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_accounting_exports_org_idempotency')
    )
    op.create_index(op.f('ix_accounting_exports_organization_id'), 'accounting_exports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounting_exports_status'), 'accounting_exports', ['status'], unique=False)
    op.create_table('invoice_extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_extractions_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_extractions')),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_invoice_extractions_invoice_id'))
    )
    op.create_index(op.f('ix_invoice_extractions_organization_id'), 'invoice_extractions', ['organization_id'], unique=False)
    op.create_table('invoice_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_invoice_files_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_files_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_files')),
    sa.UniqueConstraint('invoice_id', 'file_id', name='uq_invoice_files_invoice_file')
    )
    op.create_index(op.f('ix_invoice_files_file_id'), 'invoice_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_invoice_files_invoice_id'), 'invoice_files', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_files_organization_id'), 'invoice_files', ['organization_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_organization_id'), 'invoice_line_items', ['organization_id'], unique=False)
    op.create_table('invoice_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('contract_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_request_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_matches_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_matches')),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_invoice_matches_invoice_id'))
    )
    op.create_index(op.f('ix_invoice_matches_application_id'), 'invoice_matches', ['application_id'], unique=False)
    op.create_index(op.f('ix_invoice_matches_contract_id'), 'invoice_matches', ['contract_id'], unique=False)
    op.create_index(op.f('ix_invoice_matches_organization_id'), 'invoice_matches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoice_matches_purchase_request_id'), 'invoice_matches', ['purchase_request_id'], unique=False)
    op.create_index(op.f('ix_invoice_matches_transaction_id'), 'invoice_matches', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_invoice_matches_vendor_id'), 'invoice_matches', ['vendor_id'], unique=False)
    op.create_table('invoice_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('confirmed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_versions_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_versions')),
    sa.UniqueConstraint('invoice_id', 'version', name='uq_invoice_versions_invoice_version')
    )
    op.create_index(op.f('ix_invoice_versions_invoice_id'), 'invoice_versions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_versions_organization_id'), 'invoice_versions', ['organization_id'], unique=False)
    op.create_table('accounting_sync_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('export_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_version', sa.Integer(), nullable=False),
    sa.Column('external_version', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['accounting_exports.id'], name=op.f('fk_accounting_sync_records_export_id_accounting_exports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_sync_records'))
    )
    op.create_index(op.f('ix_accounting_sync_records_export_id'), 'accounting_sync_records', ['export_id'], unique=False)
    op.create_index(op.f('ix_accounting_sync_records_organization_id'), 'accounting_sync_records', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_sync_records_organization_id'), table_name='accounting_sync_records')
    op.drop_index(op.f('ix_accounting_sync_records_export_id'), table_name='accounting_sync_records')
    op.drop_table('accounting_sync_records')
    op.drop_index(op.f('ix_invoice_versions_organization_id'), table_name='invoice_versions')
    op.drop_index(op.f('ix_invoice_versions_invoice_id'), table_name='invoice_versions')
    op.drop_table('invoice_versions')
    op.drop_index(op.f('ix_invoice_matches_vendor_id'), table_name='invoice_matches')
    op.drop_index(op.f('ix_invoice_matches_transaction_id'), table_name='invoice_matches')
    op.drop_index(op.f('ix_invoice_matches_purchase_request_id'), table_name='invoice_matches')
    op.drop_index(op.f('ix_invoice_matches_organization_id'), table_name='invoice_matches')
    op.drop_index(op.f('ix_invoice_matches_contract_id'), table_name='invoice_matches')
    op.drop_index(op.f('ix_invoice_matches_application_id'), table_name='invoice_matches')
    op.drop_table('invoice_matches')
    op.drop_index(op.f('ix_invoice_line_items_organization_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoice_files_organization_id'), table_name='invoice_files')
    op.drop_index(op.f('ix_invoice_files_invoice_id'), table_name='invoice_files')
    op.drop_index(op.f('ix_invoice_files_file_id'), table_name='invoice_files')
    op.drop_table('invoice_files')
    op.drop_index(op.f('ix_invoice_extractions_organization_id'), table_name='invoice_extractions')
    op.drop_table('invoice_extractions')
    op.drop_index(op.f('ix_accounting_exports_status'), table_name='accounting_exports')
    op.drop_index(op.f('ix_accounting_exports_organization_id'), table_name='accounting_exports')
    op.drop_table('accounting_exports')
    op.drop_index(op.f('ix_invoices_vendor_name_normalized'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_duplicate_of_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_accounting_mappings_scope_type'), table_name='accounting_mappings')
    op.drop_index(op.f('ix_accounting_mappings_organization_id'), table_name='accounting_mappings')
    op.drop_table('accounting_mappings')
    # ### end Alembic commands ###
